# Generated by Django 5.2.1 on 2025-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mysb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('laname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('adhar', models.ImageField(upload_to='')),
                ('dob', models.DateField()),
                ('pin', models.ImageField(upload_to='')),
                ('password', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
