# Generated by Django 5.2.1 on 2025-05-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysb',
            name='id',
        ),
        migrations.AddField(
            model_name='mysb',
            name='accno',
            field=models.IntegerField(default=1001, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mysb',
            name='adhar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mysb',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
