# Generated by Django 5.2.1 on 2025-06-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_remove_mysb_id_mysb_accno_alter_mysb_adhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysb',
            name='accno',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
