# Generated by Django 5.2.1 on 2025-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_mysb_accno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysb',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
