# Generated by Django 5.2.1 on 2025-06-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_alter_mysb_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('accno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ammount', models.IntegerField()),
            ],
        ),
    ]
