# Generated by Django 5.2.1 on 2025-06-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('accno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ammount', models.IntegerField()),
            ],
        ),
    ]
