# Generated by Django 5.2.1 on 2025-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_withdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancCheck',
            fields=[
                ('accno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
