# Generated by Django 5.2.1 on 2025-06-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_balanccheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('accno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pin', models.IntegerField()),
                ('haccno', models.IntegerField()),
                ('ammount', models.IntegerField()),
                ('cammount', models.IntegerField()),
            ],
        ),
    ]
