# Generated by Django 5.2.1 on 2025-06-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='ammount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='cammount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
