# Generated by Django 5.2.1 on 2025-06-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0009_alter_transfer_ammount_alter_transfer_cammount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniStatement',
            fields=[
                ('accno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('creadit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deabit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ref_no', models.IntegerField(default=5013)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
