# Generated by Django 5.2.1 on 2025-06-15 18:33

import bankapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_ministatement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ministatement',
            old_name='creadit',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='ministatement',
            old_name='deabit',
            new_name='debit',
        ),
        migrations.AddField(
            model_name='ministatement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ministatement',
            name='accno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ministatement',
            name='ref_no',
            field=models.IntegerField(default=bankapp.models.generate_ref_no),
        ),
    ]
