# Generated by Django 5.2.1 on 2025-06-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0011_rename_creadit_ministatement_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accno', models.IntegerField()),
                ('npassword', models.CharField(max_length=10)),
                ('rpassword', models.CharField(max_length=10)),
            ],
        ),
    ]
